<?php

use Illuminate\Database\Seeder;

class DasWilClusterdesaAikmelTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('das_wil_clusterdesa')->delete();
        
        \DB::table('das_wil_clusterdesa')->insert(array (
            0 => 
            array (
                'id' => 1,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            1 => 
            array (
                'id' => 2,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            2 => 
            array (
                'id' => 3,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            3 => 
            array (
                'id' => 4,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            4 => 
            array (
                'id' => 5,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            6 => 
            array (
                'id' => 7,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            7 => 
            array (
                'id' => 8,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            8 => 
            array (
                'id' => 9,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            9 => 
            array (
                'id' => 10,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            10 => 
            array (
                'id' => 11,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            12 => 
            array (
                'id' => 13,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            13 => 
            array (
                'id' => 14,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            26 => 
            array (
                'id' => 27,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            27 => 
            array (
                'id' => 28,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            28 => 
            array (
                'id' => 29,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            29 => 
            array (
                'id' => 30,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            31 => 
            array (
                'id' => 32,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            32 => 
            array (
                'id' => 33,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            33 => 
            array (
                'id' => 34,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            34 => 
            array (
                'id' => 35,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            35 => 
            array (
                'id' => 36,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            36 => 
            array (
                'id' => 37,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            37 => 
            array (
                'id' => 38,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            38 => 
            array (
                'id' => 39,
                'rt' => '04',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            39 => 
            array (
                'id' => 40,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            40 => 
            array (
                'id' => 41,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            41 => 
            array (
                'id' => 42,
                'rt' => '00',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            42 => 
            array (
                'id' => 43,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            43 => 
            array (
                'id' => 44,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            44 => 
            array (
                'id' => 45,
                'rt' => '00',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            45 => 
            array (
                'id' => 46,
                'rt' => '00',
                'rw' => '00',
                'dusun' => 'EROT DAYA',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            46 => 
            array (
                'id' => 47,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            47 => 
            array (
                'id' => 48,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            48 => 
            array (
                'id' => 49,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            49 => 
            array (
                'id' => 50,
                'rt' => '04',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            50 => 
            array (
                'id' => 51,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG BONGKOT',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            51 => 
            array (
                'id' => 52,
                'rt' => '00',
                'rw' => '00',
                'dusun' => 'DASAN RE',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            52 => 
            array (
                'id' => 53,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            53 => 
            array (
                'id' => 54,
                'rt' => '04',
                'rw' => '00',
                'dusun' => 'LENDANG KARANG',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            54 => 
            array (
                'id' => 55,
                'rt' => '0',
                'rw' => '0',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            55 => 
            array (
                'id' => 56,
                'rt' => '0',
                'rw' => '-',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            56 => 
            array (
                'id' => 57,
                'rt' => '-',
                'rw' => '-',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            57 => 
            array (
                'id' => 58,
                'rt' => '0',
                'rw' => '00',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            58 => 
            array (
                'id' => 59,
                'rt' => '-',
                'rw' => '00',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            59 => 
            array (
                'id' => 60,
                'rt' => '01',
                'rw' => '00',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            60 => 
            array (
                'id' => 61,
                'rt' => '04',
                'rw' => '00',
                'dusun' => 'EROT LAUK',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            61 => 
            array (
                'id' => 62,
                'rt' => '02',
                'rw' => '00',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            62 => 
            array (
                'id' => 63,
                'rt' => '03',
                'rw' => '00',
                'dusun' => 'RAHAYU',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
            63 => 
            array (
                'id' => 64,
                'rt' => '04',
                'rw' => '00',
                'dusun' => 'KAMPUNG MUHAJIRIN',
                'id_kepala' => 0,
                'lat' => '',
                'lng' => '',
                'zoom' => 0,
                'path' => '',
                'map_tipe' => '',
            ),
        ));
        
        
    }
}