version: '3'
services:
  webserver:
    image: 'nginx:alpine'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './:/var/www'
      - './.docker/nginx/conf.d:/etc/nginx/conf.d/'
    networks:
      - opendk
    depends_on:
      - app
      - mysql
      - redis
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    working_dir: '/var/www'
    volumes:
      - './:/var/www'
      - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - opendk
  mysql:
    image: 'mariadb:10.3'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'opendkmysql:/var/lib/database'
    networks:
      - opendk
  mysqltest:
    image: 'mariadb:10.3'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}_test'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'opendkmysqltest:/var/lib/database'
    networks:
      - opendk
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'opendkredis:/data'
    networks:
      - opendk
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
        - opendk
networks:
  opendk:
    driver: bridge
volumes:
  opendkmysql:
    driver: local
  opendkmysqltest:
    driver: local
  opendkredis:
    driver: local

