name: Composer

on:
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  composer:
    name: composer.json in PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.4", "8.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate composer.json
        run: composer validate --strict
      - name: Install dependencies
        run: composer update --ansi --no-interaction
