name: Deploy Laravel with Ansible

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ansible Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Create inventory file
        run: |
          cat <<EOF > inventory.yml
          all:
            hosts:
              target:
                ansible_host: ${{ secrets.SERVER_IP }}
                ansible_user: ${{ secrets.SERVER_USER }}
                ansible_ssh_private_key_file: ~/.ssh/id_rsa
          EOF

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
